Soft Skills:
  - title: Communication(krerfeorf)
    labels:
      - Development need
      - Bar
      - Excellent
      - Leading
  - title: Teamwork
    labels:
      - Development need
      - Bar
      - Excellent
      - Leading
  - title: Teamwork
    labels:
      - Development need
      - Bar
      - Excellent
      - Leading
  - title: Teamwork
    labels:
      - Development need
      - Bar
      - Excellent
      - Leading