app:
  title: My Company Catalog               
  baseUrl: http://localhost:3000          


  teamAssessment:
    enabled: true                       

organization:
  name: My Company

backend:

  baseUrl: http://localhost:7007

  listen:
    port: 7007                        



  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}             
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}

proxy:
  endpoints:
    '/assessment-api':
      target: http://localhost:7007/api/team-assessment
      changeOrigin: true
      pathRewrite:
        '^/assessment-api': ''
      headers:
        X-Custom-Source: backstage

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}


techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

    guest: {}


catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration

  rules:
    - allow: [Component, System, API, Resource, Location, User, Group]

  locations:
    - type: file
      target: ./examples/entities.yaml

    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]


  useUrlReadersSearch: true


permission:
  enabled: true
